# Generated by Django 3.2.19 on 2023-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('need', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=45)),
                ('reject_reason', models.CharField(max_length=45)),
                ('uploaded_documents', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
    ]
