# Generated by Django 3.2.19 on 2023-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('contact_no', models.CharField(max_length=45)),
                ('email_id', models.CharField(max_length=45)),
                ('batch', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
